# Generated by Django 6.1.1 on 2026-09-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_restaurant_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
